### PR TITLE
Fix typo on hiring process page

### PR DESCRIPTION
**Pull request by fureigh**
`Accomodations` --> `Accommodations`

Relates to issue #212.

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/join.tts.gsa.gov/BRANCH_NAME/)

Changes proposed in this pull request:
- Change `Accomodations` to `Accommodations`

/cc @nickttng (...? That's my best guess from reading #212. Thanks in advance!)

### CODE REVIEW

**Comment by nickttng** [comment]
👋🏼  Fureigh - Thanks for the tag. Based on the recent approvers, I think @omargonzalez-tts and @Pattybryan would approve any changes to the JoinTTS site.

**Review by PattyDecarli — APPROVED** [review]
approved

**Review by PattyDecarli — CHANGES_REQUESTED** [review]
Please close this pull request! We will create the request from the talent team and make the update. Thank you for bringing to our attention!

**Comment by PattyDecarli** [comment]
Closing, as this has been resolved on our end with a PR. Thank you!

**Pull request closed without merging**
