### PR TITLE
Force-polling seems to fix auto-regeneration for Windows

### PR DESCRIPTION
**Pull request by ctro**
A small change that should make the local dev experience in Windows better.

### CODE REVIEW

**Comment by ctro** [comment]
Bill, check this out on your machine, it works on my Windows machine.
If you fire up Docker, and change the contents of some page the site _should_ re-generate.
You should see output in the `docker-compose up` terminal.

**Comment by rooneywp** [comment]
I may not be doing something right, it's not reloading. I can see the file change in the PR. If I make a change I don't see any docker activity in the terminal or on the site. But if stop and compose up again, I do see the change on the local site.

**Comment by rooneywp** [comment]
This worked for me.

"check out the `force-polling` branch, then `<ctrl>-c`, then `docker-compose build` then `docker-compose up`"

**Comment by ctro** [comment]
Right!  The thing to remember is that changes to files _other than the files that make the website_ will require stopping/starting docker-compose.

**Pull request merged**
