### PR TITLE
cloud.gov consulting technical lead draft job announcement

### PR DESCRIPTION
**Pull request by JennMoran**

### CODE REVIEW

**Comment by JennMoran** [comment]
@LeighFinkel please review the upcoming announcement for the cloud.gov consulting lead role here: https://federalist-proxy.app.cloud.gov/preview/18f/join.tts.gsa.gov/cloud.gov-draft/join/cloud.gov-consulting-technical-lead/

If all looks good you can go ahead and merge the pull request to make the role live.  Thanks!

**Comment by LeighFinkel** [comment]
@JennMoran 
- can you remove "Applications will be open for submission on ." from the first paragraph?
- key objective 2,3 and 4 both need the end of the objective fixed - they are not bold and are on the next line

Thanks!
-

**Comment by JennMoran** [comment]
@LeighFinkel edits done. please review one last time and merge is all good. thanks!

**Comment by JennMoran** [comment]
@rooneywp the second part of the first paragraph is not showing up in the preview.  First paragraph needs to say:

The target date for when this position will officially open for application has not yet been determined. If you’d like to be notified when this position is open, sign up to our mailing list.

**Comment by JennMoran** [comment]
@leigh made one last edit: updated salary range to be Boston only (only a slight difference). Merging.

**Pull request merged**
