### PR TITLE
Example resume format and notes

### PR DESCRIPTION
**Pull request by amandacostello**
Changes proposed in this pull request:
- Example federal resume with my notes, a new page
- Approved by TTS Talent team 

/cc @JennMoran @Elizscott

### CODE REVIEW

**Comment by JennMoran** [comment]
@amandacostello  can you please send me the preview link - i don't see this build on our website when I go to the federalist page.

**Comment by amandacostello** [comment]
Does this link work? I'm still figuring out GitHub!

https://github.com/amandacostello/join.tts.gsa.gov/blob/master/pages/example_resume.md

**Comment by JennMoran** [comment]
The technical skills in your example to not align with the directions given in the first part. 

Also - let's keep this out of the joinpage.  @keithrwilson  can we find a home for this content in the handbook, perhaps under the Hiring page?  

The plan was to put this content in the handbook and then link to that page from the resume section on our join site. 

Thank you!

**Comment by amandacostello** [comment]
The list of technical skills is what I had listed on my federal resume 😬.   

Totally cool if this could live in the 18F handbook somewhere, I'm just hoping to get a link I can share out ASAP, since the content strategist job is live! 😺

**Comment by JennMoran** [comment]
You'll need to edit the technical skills from your resume otherwise people will just right it as a list and may not be found qualified 

@keithrwilson once Amanda makes the edits please put this in our handbook page and send us the link. thank you!

**Comment by amandacostello** [comment]
@JennMoran I've got that content updated, thanks!
@keithrwilson this is all yours. :)

**Comment by nickttng** [comment]
@keithrwilson and others - I'm working on updating the JoinTTS and it looks like the checks hasn't been functioning. Has this been going for a while? I can check with a dev to see what's up with this.

**Comment by JennMoran** [comment]
@nickttng this pull request actually should actually be closed - this content was moved to the handbook instead

**Comment by nickttng** [comment]
Thanks for the update. Closing.

**Pull request closed without merging**
