### PR TITLE
Update TTS Offices text

### PR DESCRIPTION
**Pull request by awfrancisco**
Fixes issue(s) #173 #149  .

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/join.tts.gsa.gov/offices/)

Changes proposed in this pull request:
- Changes description of TTS offices
- Adds a line summarizing the type of projects the four main TTS offices work on
- Adds a case study for each of the four main offices
- Updates the open positions link that's displayed on closed job postings

**Needs**
This page could really use some design/formatting help. 

/cc @nickttng @JennMoran

### CODE REVIEW

**Comment by awfrancisco** [comment]
Looks like this PR is failing on a timeout to this link in the position template https://www.sss.gov/Registration-Info/Who-Registration. The link works fine for me. Any ideas @ctro?

**Comment by ctro** [comment]
@awfrancisco yes -- that test fails inconsistently for me.

The sss.gov site is just _really_ slow to respond sometimes.  For now the failed build won't stop you from merging the PR, so no real worries.

@rooneywp and I are working through some PRs that will help this out. 

 I played with bumping timeouts to 30 seconds, but even that didn't always work, and it slows down the test suite considerably.  So what I propose in the PR is to disable checking external links (all internal site links are still checked).  The obv. downside is that we won't check that links like the one to sss.gov actually resolve.

Here's the change:
https://github.com/18F/join.tts.gsa.gov/blob/9a3fbf1993d961371bd30525715e3d617276504c/Rakefile#L7

Here' s the PR if you want to weigh in on the change:
https://github.com/18F/join.tts.gsa.gov/pull/188

**Comment by awfrancisco** [comment]
That change sounds good to me. Looks like the federalist staging is now throwing an error. Any ideas on that one?

**Comment by ctro** [comment]
`Details` goes here: https://federalistapp-staging.18f.gov/sites/129/builds/11633/logs which reports `Whoops, our S3 keys were rotated during your build and became out of date. This was not a problem with your site build,`

You can also manually `rebuild branch` from the Federalist interface

**Comment by ctro** [comment]
the staging link looks like it's working I think?  https://federalist-proxy.app.cloud.gov/preview/18f/join.tts.gsa.gov/offices/  (this is the 😎 link above)

**Comment by awfrancisco** [comment]
Yup, preview looks good to me. This is ready to merge when @JennMoran reviews.

**Comment by JennMoran** [comment]
looks good to me

**Pull request merged**
