### PR TITLE
Change newsletter subscription flow

### PR DESCRIPTION
**Pull request by awfrancisco**
[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/join.tts.gsa.gov/newsletter/)

Changes proposed in this pull request:
- Adds a new `Get job alerts` page with required subscription question
- Removes GovDelivery popup
- Changes front page newsletter link to new page
- Adds new page to left hand nav
- Changers link on include for closed positions

/cc @JennMoran

### CODE REVIEW

**Comment by JennMoran** [comment]
@awfrancisco looks good!
The following areas will need to be updated with the new sign-up link:
- index page
- all the job announcements in our positions folder
- upcoming statement: https://github.com/18F/join.tts.gsa.gov/blob/master/_includes/upcoming_statement.html

Let me know when you plan to get this up. Thanks!

**Comment by awfrancisco** [comment]
This PR already updates the index and the upcoming statement. Looks like the jobs in the position folder still link to the old Google form, but I'll go update those.

**Comment by rooneywp** [comment]
@awfrancisco Went through the sign-up flow and noticed a couple things. 

First, the roles question still isn't required to go to the next step. Apologies if this was already discussed, are we not able to make it required? If not, then presenting it this way seems like the best we'll be able to do.

Second, after clicking Next, I was taken to this screen:

image

This seems confusing, is there a way that we can bypass this?

**Comment by awfrancisco** [comment]
The role question should have been required. I'll reach out to see why that didn't happen. 

That next screen is the "GovDelivery Network" - it shows subscribers other GovDelivery subscriptions they might be interested in and is a big part of the platform. Helps you get new subscribers. I think we could opt out of the network, but then we also wouldn't get those subscribers from other lists. As a note, I don't think people have to complete this page to be subscribed. I believe they are added to the list as soon as they complete the first page. Happy to grab some time to talk further if you'd like.

**Comment by awfrancisco** [comment]
Ok, all the questions are required now.

**Comment by JennMoran** [comment]
@awfrancisco please opt us out of the network.  that page is confusing and would cause a lot of people to email us asking what it means.  We are ok not getting subscribers from those lists.   thanks

**Comment by awfrancisco** [comment]
So, the network subscriber page is mandatory, but we can add text at the top to explain that people have already signed up for the mailing list and these are other lists they might be interested in. Happy to schedule a meeting if you'd like to discuss. Here's some proposed text we could add to the page:

> Thank you for subscribing to receive job alerts from the TTS Talent Team. We'll send you an email when we have an open position that matches your interests.
> 
> Below are some other organizations and newsletters that you may be interested in. Subscribe by checking the boxes. By clicking "Next", you're sending your email address to these organizations.

**Comment by JennMoran** [comment]
I'm OK with that language.  Thank you!

**Comment by awfrancisco** [comment]
That language is added to the network page now. This is ready for another review.

**Pull request merged**
