### PR TITLE
Update site.scss

### PR DESCRIPTION
**Pull request by nickttng**
This update is a visual refresh. Partially fixes issue(s) #176 and #177. For both issues, what's left is updating the footer design.

Changes proposed in this pull request:
- Typographic styles
- Banner
- Header section with menu button
- Sidebar nav

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/join.tts.gsa.gov/visual-refresh-01/)

Screenshot previews (left is current; right is the update)
jointts-mobile
jointts-desktop

/cc @Dahianna @JennMoran

### CODE REVIEW

**Comment by Dahianna** [comment]
Looks great! Can we add a twitter icon in the bottom bar that links to the [TTS account](https://twitter.com/GSA_TTS) or should we do it after we merge?

**Comment by nickttng** [comment]
@Dahianna We will add a Twitter icon after we merge. The addition will be part of a new footer design in the next stage of change. Works for you?

**Comment by Dahianna** [comment]
Yes! I'll go ahead and merge. Thank you!

**Comment by Dahianna** [comment]
Merged!

**Pull request merged**
